Attribute VB_Name = "MMsgLookup"
Option Explicit

Private Const WM_NULL                         As Long = &H0
Private Const WM_CREATE                       As Long = &H1
Private Const WM_DESTROY                      As Long = &H2
Private Const WM_MOVE                         As Long = &H3
Private Const WM_SIZE                         As Long = &H5
Private Const WM_ACTIVATE                     As Long = &H6
Private Const WM_SETFOCUS                     As Long = &H7
Private Const WM_KILLFOCUS                    As Long = &H8
Private Const WM_ENABLE                       As Long = &HA
Private Const WM_SETREDRAW                    As Long = &HB
Private Const WM_SETTEXT                      As Long = &HC
Private Const WM_GETTEXT                      As Long = &HD
Private Const WM_GETTEXTLENGTH                As Long = &HE
Private Const WM_PAINT                        As Long = &HF
Private Const WM_CLOSE                        As Long = &H10
Private Const WM_QUERYENDSESSION              As Long = &H11
Private Const WM_QUIT                         As Long = &H12
Private Const WM_QUERYOPEN                    As Long = &H13
Private Const WM_ERASEBKGND                   As Long = &H14
Private Const WM_SYSCOLORCHANGE               As Long = &H15
Private Const WM_ENDSESSION                   As Long = &H16
Private Const WM_SHOWWINDOW                   As Long = &H18
Private Const WM_SETTINGCHANGE                As Long = &H1A
Private Const WM_DEVMODECHANGE                As Long = &H1B
Private Const WM_ACTIVATEAPP                  As Long = &H1C
Private Const WM_FONTCHANGE                   As Long = &H1D
Private Const WM_TIMECHANGE                   As Long = &H1E
Private Const WM_CANCELMODE                   As Long = &H1F
Private Const WM_SETCURSOR                    As Long = &H20
Private Const WM_MOUSEACTIVATE                As Long = &H21
Private Const WM_CHILDACTIVATE                As Long = &H22
Private Const WM_QUEUESYNC                    As Long = &H23
Private Const WM_GETMINMAXINFO                As Long = &H24
Private Const WM_PAINTICON                    As Long = &H26
Private Const WM_ICONERASEBKGND               As Long = &H27
Private Const WM_NEXTDLGCTL                   As Long = &H28
Private Const WM_SPOOLERSTATUS                As Long = &H2A
Private Const WM_DRAWITEM                     As Long = &H2B
Private Const WM_MEASUREITEM                  As Long = &H2C
Private Const WM_DELETEITEM                   As Long = &H2D
Private Const WM_VKEYTOITEM                   As Long = &H2E
Private Const WM_CHARTOITEM                   As Long = &H2F
Private Const WM_SETFONT                      As Long = &H30
Private Const WM_GETFONT                      As Long = &H31
Private Const WM_SETHOTKEY                    As Long = &H32
Private Const WM_GETHOTKEY                    As Long = &H33
Private Const WM_QUERYDRAGICON                As Long = &H37
Private Const WM_COMPAREITEM                  As Long = &H39
Private Const WM_GETOBJECT                    As Long = &H3D
Private Const WM_COMPACTING                   As Long = &H41
Private Const WM_COMMNOTIFY                   As Long = &H44
Private Const WM_WINDOWPOSCHANGING            As Long = &H46
Private Const WM_WINDOWPOSCHANGED             As Long = &H47
Private Const WM_POWER                        As Long = &H48
Private Const WM_COPYDATA                     As Long = &H4A
Private Const WM_CANCELJOURNAL                As Long = &H4B
Private Const WM_NOTIFY                       As Long = &H4E
Private Const WM_INPUTLANGCHANGEREQUEST       As Long = &H50
Private Const WM_INPUTLANGCHANGE              As Long = &H51
Private Const WM_TCARD                        As Long = &H52
Private Const WM_HELP                         As Long = &H53
Private Const WM_USERCHANGED                  As Long = &H54
Private Const WM_NOTIFYFORMAT                 As Long = &H55
Private Const WM_CONTEXTMENU                  As Long = &H7B
Private Const WM_STYLECHANGING                As Long = &H7C
Private Const WM_STYLECHANGED                 As Long = &H7D
Private Const WM_DISPLAYCHANGE                As Long = &H7E
Private Const WM_GETICON                      As Long = &H7F
Private Const WM_SETICON                      As Long = &H80
Private Const WM_NCCREATE                     As Long = &H81
Private Const WM_NCDESTROY                    As Long = &H82
Private Const WM_NCCALCSIZE                   As Long = &H83
Private Const WM_NCHITTEST                    As Long = &H84
Private Const WM_NCPAINT                      As Long = &H85
Private Const WM_NCACTIVATE                   As Long = &H86
Private Const WM_GETDLGCODE                   As Long = &H87
Private Const WM_SYNCPAINT                    As Long = &H88
Private Const WM_NCMOUSEMOVE                  As Long = &HA0
Private Const WM_NCLBUTTONDOWN                As Long = &HA1
Private Const WM_NCLBUTTONUP                  As Long = &HA2
Private Const WM_NCLBUTTONDBLCLK              As Long = &HA3
Private Const WM_NCRBUTTONDOWN                As Long = &HA4
Private Const WM_NCRBUTTONUP                  As Long = &HA5
Private Const WM_NCRBUTTONDBLCLK              As Long = &HA6
Private Const WM_NCMBUTTONDOWN                As Long = &HA7
Private Const WM_NCMBUTTONUP                  As Long = &HA8
Private Const WM_NCMBUTTONDBLCLK              As Long = &HA9
Private Const WM_NCXBUTTONDOWN                As Long = &HAB
Private Const WM_NCXBUTTONUP                  As Long = &HAC
Private Const WM_NCXBUTTONDBLCLK              As Long = &HAD
Private Const WM_INPUT                        As Long = &HFF
Private Const WM_KEYFIRST                     As Long = &H100
Private Const WM_KEYDOWN                      As Long = &H100
Private Const WM_KEYUP                        As Long = &H101
Private Const WM_CHAR                         As Long = &H102
Private Const WM_DEADCHAR                     As Long = &H103
Private Const WM_SYSKEYDOWN                   As Long = &H104
Private Const WM_SYSKEYUP                     As Long = &H105
Private Const WM_SYSCHAR                      As Long = &H106
Private Const WM_SYSDEADCHAR                  As Long = &H107
Private Const WM_KEYLAST                      As Long = &H108
Private Const WM_IME_STARTCOMPOSITION         As Long = &H10D
Private Const WM_IME_ENDCOMPOSITION           As Long = &H10E
Private Const WM_IME_COMPOSITION              As Long = &H10F
Private Const WM_INITDIALOG                   As Long = &H110
Private Const WM_COMMAND                      As Long = &H111
Private Const WM_SYSCOMMAND                   As Long = &H112
Private Const WM_TIMER                        As Long = &H113
Private Const WM_HSCROLL                      As Long = &H114
Private Const WM_VSCROLL                      As Long = &H115
Private Const WM_INITMENU                     As Long = &H116
Private Const WM_INITMENUPOPUP                As Long = &H117
Private Const WM_MENUSELECT                   As Long = &H11F
Private Const WM_MENUCHAR                     As Long = &H120
Private Const WM_ENTERIDLE                    As Long = &H121
Private Const WM_MENURBUTTONUP                As Long = &H122
Private Const WM_MENUDRAG                     As Long = &H123
Private Const WM_MENUGETOBJECT                As Long = &H124
Private Const WM_UNINITMENUPOPUP              As Long = &H125
Private Const WM_MENUCOMMAND                  As Long = &H126
Private Const WM_CHANGEUISTATE                As Long = &H127
Private Const WM_UPDATEUISTATE                As Long = &H128
Private Const WM_QUERYUISTATE                 As Long = &H129
Private Const WM_CTLCOLORMSGBOX               As Long = &H132
Private Const WM_CTLCOLOREDIT                 As Long = &H133
Private Const WM_CTLCOLORLISTBOX              As Long = &H134
Private Const WM_CTLCOLORBTN                  As Long = &H135
Private Const WM_CTLCOLORDLG                  As Long = &H136
Private Const WM_CTLCOLORSCROLLBAR            As Long = &H137
Private Const WM_CTLCOLORSTATIC               As Long = &H138
Private Const MN_GETHMENU                     As Long = &H1E1
Private Const WM_MOUSEFIRST                   As Long = &H200
Private Const WM_MOUSEMOVE                    As Long = &H200
Private Const WM_LBUTTONDOWN                  As Long = &H201
Private Const WM_LBUTTONUP                    As Long = &H202
Private Const WM_LBUTTONDBLCLK                As Long = &H203
Private Const WM_RBUTTONDOWN                  As Long = &H204
Private Const WM_RBUTTONUP                    As Long = &H205
Private Const WM_RBUTTONDBLCLK                As Long = &H206
Private Const WM_MBUTTONDOWN                  As Long = &H207
Private Const WM_MBUTTONUP                    As Long = &H208
Private Const WM_MBUTTONDBLCLK                As Long = &H209
Private Const WM_MOUSEWHEEL                   As Long = &H20A
Private Const WM_XBUTTONDOWN                  As Long = &H20B
Private Const WM_XBUTTONUP                    As Long = &H20C
Private Const WM_XBUTTONDBLCLK                As Long = &H20D
Private Const WM_PARENTNOTIFY                 As Long = &H210
Private Const WM_ENTERMENULOOP                As Long = &H211
Private Const WM_EXITMENULOOP                 As Long = &H212
Private Const WM_NEXTMENU                     As Long = &H213
Private Const WM_SIZING                       As Long = &H214
Private Const WM_CAPTURECHANGED               As Long = &H215
Private Const WM_MOVING                       As Long = &H216
Private Const WM_POWERBROADCAST               As Long = &H218
Private Const WM_DEVICECHANGE                 As Long = &H219
Private Const WM_MDICREATE                    As Long = &H220
Private Const WM_MDIDESTROY                   As Long = &H221
Private Const WM_MDIACTIVATE                  As Long = &H222
Private Const WM_MDIRESTORE                   As Long = &H223
Private Const WM_MDINEXT                      As Long = &H224
Private Const WM_MDIMAXIMIZE                  As Long = &H225
Private Const WM_MDITILE                      As Long = &H226
Private Const WM_MDICASCADE                   As Long = &H227
Private Const WM_MDIICONARRANGE               As Long = &H228
Private Const WM_MDIGETACTIVE                 As Long = &H229
Private Const WM_MDISETMENU                   As Long = &H230
Private Const WM_ENTERSIZEMOVE                As Long = &H231
Private Const WM_EXITSIZEMOVE                 As Long = &H232
Private Const WM_DROPFILES                    As Long = &H233
Private Const WM_MDIREFRESHMENU               As Long = &H234
Private Const WM_IME_SETCONTEXT               As Long = &H281
Private Const WM_IME_NOTIFY                   As Long = &H282
Private Const WM_IME_CONTROL                  As Long = &H283
Private Const WM_IME_COMPOSITIONFULL          As Long = &H284
Private Const WM_IME_SELECT                   As Long = &H285
Private Const WM_IME_CHAR                     As Long = &H286
Private Const WM_IME_REQUEST                  As Long = &H288
Private Const WM_IME_KEYDOWN                  As Long = &H290
Private Const WM_IME_KEYUP                    As Long = &H291
Private Const WM_MOUSEHOVER                   As Long = &H2A1
Private Const WM_MOUSELEAVE                   As Long = &H2A3
Private Const WM_NCMOUSEHOVER                 As Long = &H2A0
Private Const WM_NCMOUSELEAVE                 As Long = &H2A2
Private Const WM_WTSSESSION_CHANGE            As Long = &H2B1
Private Const WM_TABLET_FIRST                 As Long = &H2C0
Private Const WM_TABLET_LAST                  As Long = &H2DF
Private Const WM_CUT                          As Long = &H300
Private Const WM_COPY                         As Long = &H301
Private Const WM_PASTE                        As Long = &H302
Private Const WM_CLEAR                        As Long = &H303
Private Const WM_UNDO                         As Long = &H304
Private Const WM_RENDERFORMAT                 As Long = &H305
Private Const WM_RENDERALLFORMATS             As Long = &H306
Private Const WM_DESTROYCLIPBOARD             As Long = &H307
Private Const WM_DRAWCLIPBOARD                As Long = &H308
Private Const WM_PAINTCLIPBOARD               As Long = &H309
Private Const WM_VSCROLLCLIPBOARD             As Long = &H30A
Private Const WM_SIZECLIPBOARD                As Long = &H30B
Private Const WM_ASKCBFORMATNAME              As Long = &H30C
Private Const WM_CHANGECBCHAIN                As Long = &H30D
Private Const WM_HSCROLLCLIPBOARD             As Long = &H30E
Private Const WM_QUERYNEWPALETTE              As Long = &H30F
Private Const WM_PALETTEISCHANGING            As Long = &H310
Private Const WM_PALETTECHANGED               As Long = &H311
Private Const WM_HOTKEY                       As Long = &H312
Private Const WM_PRINT                        As Long = &H317
Private Const WM_PRINTCLIENT                  As Long = &H318
Private Const WM_APPCOMMAND                   As Long = &H319
Private Const WM_THEMECHANGED                 As Long = &H31A
Private Const WM_HANDHELDFIRST                As Long = &H358
Private Const WM_HANDHELDLAST                 As Long = &H35F
Private Const WM_AFXFIRST                     As Long = &H360
Private Const WM_AFXLAST                      As Long = &H37F
Private Const WM_PENWINFIRST                  As Long = &H380
Private Const WM_PENWINLAST                   As Long = &H38F
Private Const WM_DDE_INITIATE                 As Long = &H3E0
Private Const WM_DDE_TERMINATE                As Long = &H3E1
Private Const WM_DDE_ADVISE                   As Long = &H3E2
Private Const WM_DDE_UNADVISE                 As Long = &H3E3
Private Const WM_DDE_ACK                      As Long = &H3E4
Private Const WM_DDE_DATA                     As Long = &H3E5
Private Const WM_DDE_REQUEST                  As Long = &H3E6
Private Const WM_DDE_POKE                     As Long = &H3E7
Private Const WM_DDE_EXECUTE                  As Long = &H3E8
Private Const WM_USER                         As Long = &H400

'/*
' * Parameter for SystemParametersInfo()
' */
Private Const SPI_GETBEEP                       As Long = &H1
Private Const SPI_SETBEEP                       As Long = &H2
Private Const SPI_GETMOUSE                      As Long = &H3
Private Const SPI_SETMOUSE                      As Long = &H4
Private Const SPI_GETBORDER                     As Long = &H5
Private Const SPI_SETBORDER                     As Long = &H6
Private Const SPI_GETKEYBOARDSPEED              As Long = &HA
Private Const SPI_SETKEYBOARDSPEED              As Long = &HB
Private Const SPI_LANGDRIVER                    As Long = &HC
Private Const SPI_ICONHORIZONTALSPACING         As Long = &HD
Private Const SPI_GETSCREENSAVETIMEOUT          As Long = &HE
Private Const SPI_SETSCREENSAVETIMEOUT          As Long = &HF
Private Const SPI_GETSCREENSAVEACTIVE           As Long = &H10
Private Const SPI_SETSCREENSAVEACTIVE           As Long = &H11
Private Const SPI_GETGRIDGRANULARITY            As Long = &H12
Private Const SPI_SETGRIDGRANULARITY            As Long = &H13
Private Const SPI_SETDESKWALLPAPER              As Long = &H14
Private Const SPI_SETDESKPATTERN                As Long = &H15
Private Const SPI_GETKEYBOARDDELAY              As Long = &H16
Private Const SPI_SETKEYBOARDDELAY              As Long = &H17
Private Const SPI_ICONVERTICALSPACING           As Long = &H18
Private Const SPI_GETICONTITLEWRAP              As Long = &H19
Private Const SPI_SETICONTITLEWRAP              As Long = &H1A
Private Const SPI_GETMENUDROPALIGNMENT          As Long = &H1B
Private Const SPI_SETMENUDROPALIGNMENT          As Long = &H1C
Private Const SPI_SETDOUBLECLKWIDTH             As Long = &H1D
Private Const SPI_SETDOUBLECLKHEIGHT            As Long = &H1E
Private Const SPI_GETICONTITLELOGFONT           As Long = &H1F
Private Const SPI_SETDOUBLECLICKTIME            As Long = &H20
Private Const SPI_SETMOUSEBUTTONSWAP            As Long = &H21
Private Const SPI_SETICONTITLELOGFONT           As Long = &H22
Private Const SPI_GETFASTTASKSWITCH             As Long = &H23
Private Const SPI_SETFASTTASKSWITCH             As Long = &H24
Private Const SPI_SETDRAGFULLWINDOWS            As Long = &H25
Private Const SPI_GETDRAGFULLWINDOWS            As Long = &H26
Private Const SPI_GETNONCLIENTMETRICS           As Long = &H29
Private Const SPI_SETNONCLIENTMETRICS           As Long = &H2A
Private Const SPI_GETMINIMIZEDMETRICS           As Long = &H2B
Private Const SPI_SETMINIMIZEDMETRICS           As Long = &H2C
Private Const SPI_GETICONMETRICS                As Long = &H2D
Private Const SPI_SETICONMETRICS                As Long = &H2E
Private Const SPI_SETWORKAREA                   As Long = &H2F
Private Const SPI_GETWORKAREA                   As Long = &H30
Private Const SPI_SETPENWINDOWS                 As Long = &H31
Private Const SPI_GETHIGHCONTRAST               As Long = &H42
Private Const SPI_SETHIGHCONTRAST               As Long = &H43
Private Const SPI_GETKEYBOARDPREF               As Long = &H44
Private Const SPI_SETKEYBOARDPREF               As Long = &H45
Private Const SPI_GETSCREENREADER               As Long = &H46
Private Const SPI_SETSCREENREADER               As Long = &H47
Private Const SPI_GETANIMATION                  As Long = &H48
Private Const SPI_SETANIMATION                  As Long = &H49
Private Const SPI_GETFONTSMOOTHING              As Long = &H4A
Private Const SPI_SETFONTSMOOTHING              As Long = &H4B
Private Const SPI_SETDRAGWIDTH                  As Long = &H4C
Private Const SPI_SETDRAGHEIGHT                 As Long = &H4D
Private Const SPI_SETHANDHELD                   As Long = &H4E
Private Const SPI_GETLOWPOWERTIMEOUT            As Long = &H4F
Private Const SPI_GETPOWEROFFTIMEOUT            As Long = &H50
Private Const SPI_SETLOWPOWERTIMEOUT            As Long = &H51
Private Const SPI_SETPOWEROFFTIMEOUT            As Long = &H52
Private Const SPI_GETLOWPOWERACTIVE             As Long = &H53
Private Const SPI_GETPOWEROFFACTIVE             As Long = &H54
Private Const SPI_SETLOWPOWERACTIVE             As Long = &H55
Private Const SPI_SETPOWEROFFACTIVE             As Long = &H56
Private Const SPI_SETCURSORS                    As Long = &H57
Private Const SPI_SETICONS                      As Long = &H58
Private Const SPI_GETDEFAULTINPUTLANG           As Long = &H59
Private Const SPI_SETDEFAULTINPUTLANG           As Long = &H5A
Private Const SPI_SETLANGTOGGLE                 As Long = &H5B
Private Const SPI_GETWINDOWSEXTENSION           As Long = &H5C
Private Const SPI_SETMOUSETRAILS                As Long = &H5D
Private Const SPI_GETMOUSETRAILS                As Long = &H5E
Private Const SPI_SETSCREENSAVERRUNNING         As Long = &H61
Private Const SPI_GETFILTERKEYS                 As Long = &H32
Private Const SPI_SETFILTERKEYS                 As Long = &H33
Private Const SPI_GETTOGGLEKEYS                 As Long = &H34
Private Const SPI_SETTOGGLEKEYS                 As Long = &H35
Private Const SPI_GETMOUSEKEYS                  As Long = &H36
Private Const SPI_SETMOUSEKEYS                  As Long = &H37
Private Const SPI_GETSHOWSOUNDS                 As Long = &H38
Private Const SPI_SETSHOWSOUNDS                 As Long = &H39
Private Const SPI_GETSTICKYKEYS                 As Long = &H3A
Private Const SPI_SETSTICKYKEYS                 As Long = &H3B
Private Const SPI_GETACCESSTIMEOUT              As Long = &H3C
Private Const SPI_SETACCESSTIMEOUT              As Long = &H3D
Private Const SPI_GETSERIALKEYS                 As Long = &H3E
Private Const SPI_SETSERIALKEYS                 As Long = &H3F
Private Const SPI_GETSOUNDSENTRY                As Long = &H40
Private Const SPI_SETSOUNDSENTRY                As Long = &H41
Private Const SPI_GETSNAPTODEFBUTTON            As Long = &H5F
Private Const SPI_SETSNAPTODEFBUTTON            As Long = &H60
Private Const SPI_GETMOUSEHOVERWIDTH            As Long = &H62
Private Const SPI_SETMOUSEHOVERWIDTH            As Long = &H63
Private Const SPI_GETMOUSEHOVERHEIGHT           As Long = &H64
Private Const SPI_SETMOUSEHOVERHEIGHT           As Long = &H65
Private Const SPI_GETMOUSEHOVERTIME             As Long = &H66
Private Const SPI_SETMOUSEHOVERTIME             As Long = &H67
Private Const SPI_GETWHEELSCROLLLINES           As Long = &H68
Private Const SPI_SETWHEELSCROLLLINES           As Long = &H69
Private Const SPI_GETMENUSHOWDELAY              As Long = &H6A
Private Const SPI_SETMENUSHOWDELAY              As Long = &H6B
Private Const SPI_GETSHOWIMEUI                  As Long = &H6E
Private Const SPI_SETSHOWIMEUI                  As Long = &H6F
Private Const SPI_GETMOUSESPEED                 As Long = &H70
Private Const SPI_SETMOUSESPEED                 As Long = &H71
Private Const SPI_GETSCREENSAVERRUNNING         As Long = &H72
Private Const SPI_GETDESKWALLPAPER              As Long = &H73
Private Const SPI_GETACTIVEWINDOWTRACKING       As Long = &H1000
Private Const SPI_SETACTIVEWINDOWTRACKING       As Long = &H1001
Private Const SPI_GETMENUANIMATION              As Long = &H1002
Private Const SPI_SETMENUANIMATION              As Long = &H1003
Private Const SPI_GETCOMBOBOXANIMATION          As Long = &H1004
Private Const SPI_SETCOMBOBOXANIMATION          As Long = &H1005
Private Const SPI_GETLISTBOXSMOOTHSCROLLING     As Long = &H1006
Private Const SPI_SETLISTBOXSMOOTHSCROLLING     As Long = &H1007
Private Const SPI_GETGRADIENTCAPTIONS           As Long = &H1008
Private Const SPI_SETGRADIENTCAPTIONS           As Long = &H1009
Private Const SPI_GETKEYBOARDCUES               As Long = &H100A
Private Const SPI_SETKEYBOARDCUES               As Long = &H100B
Private Const SPI_GETACTIVEWNDTRKZORDER         As Long = &H100C
Private Const SPI_SETACTIVEWNDTRKZORDER         As Long = &H100D
Private Const SPI_GETHOTTRACKING                As Long = &H100E
Private Const SPI_SETHOTTRACKING                As Long = &H100F
Private Const SPI_GETMENUFADE                   As Long = &H1012
Private Const SPI_SETMENUFADE                   As Long = &H1013
Private Const SPI_GETSELECTIONFADE              As Long = &H1014
Private Const SPI_SETSELECTIONFADE              As Long = &H1015
Private Const SPI_GETTOOLTIPANIMATION           As Long = &H1016
Private Const SPI_SETTOOLTIPANIMATION           As Long = &H1017
Private Const SPI_GETTOOLTIPFADE                As Long = &H1018
Private Const SPI_SETTOOLTIPFADE                As Long = &H1019
Private Const SPI_GETCURSORSHADOW               As Long = &H101A
Private Const SPI_SETCURSORSHADOW               As Long = &H101B
Private Const SPI_GETMOUSESONAR                 As Long = &H101C
Private Const SPI_SETMOUSESONAR                 As Long = &H101D
Private Const SPI_GETMOUSECLICKLOCK             As Long = &H101E
Private Const SPI_SETMOUSECLICKLOCK             As Long = &H101F
Private Const SPI_GETMOUSEVANISH                As Long = &H1020
Private Const SPI_SETMOUSEVANISH                As Long = &H1021
Private Const SPI_GETFLATMENU                   As Long = &H1022
Private Const SPI_SETFLATMENU                   As Long = &H1023
Private Const SPI_GETDROPSHADOW                 As Long = &H1024
Private Const SPI_SETDROPSHADOW                 As Long = &H1025
Private Const SPI_GETBLOCKSENDINPUTRESETS       As Long = &H1026
Private Const SPI_SETBLOCKSENDINPUTRESETS       As Long = &H1027
Private Const SPI_GETUIEFFECTS                  As Long = &H103E
Private Const SPI_SETUIEFFECTS                  As Long = &H103F
Private Const SPI_GETFOREGROUNDLOCKTIMEOUT      As Long = &H2000
Private Const SPI_SETFOREGROUNDLOCKTIMEOUT      As Long = &H2001
Private Const SPI_GETACTIVEWNDTRKTIMEOUT        As Long = &H2002
Private Const SPI_SETACTIVEWNDTRKTIMEOUT        As Long = &H2003
Private Const SPI_GETFOREGROUNDFLASHCOUNT       As Long = &H2004
Private Const SPI_SETFOREGROUNDFLASHCOUNT       As Long = &H2005
Private Const SPI_GETCARETWIDTH                 As Long = &H2006
Private Const SPI_SETCARETWIDTH                 As Long = &H2007
Private Const SPI_GETMOUSECLICKLOCKTIME         As Long = &H2008
Private Const SPI_SETMOUSECLICKLOCKTIME         As Long = &H2009
Private Const SPI_GETFONTSMOOTHINGTYPE          As Long = &H200A
Private Const SPI_SETFONTSMOOTHINGTYPE          As Long = &H200B
Private Const SPI_GETFONTSMOOTHINGCONTRAST      As Long = &H200C
Private Const SPI_SETFONTSMOOTHINGCONTRAST      As Long = &H200D
Private Const SPI_GETFOCUSBORDERWIDTH           As Long = &H200E
Private Const SPI_SETFOCUSBORDERWIDTH           As Long = &H200F
Private Const SPI_GETFOCUSBORDERHEIGHT          As Long = &H2010
Private Const SPI_SETFOCUSBORDERHEIGHT          As Long = &H2011
Private Const SPI_GETFONTSMOOTHINGORIENTATION   As Long = &H2012
Private Const SPI_SETFONTSMOOTHINGORIENTATION   As Long = &H2013

Public Function GetMessageName(ByVal nMsg As Long) As String
   Dim msg As String
   Select Case nMsg
      Case &H0: msg = "WM_NULL"
      Case &H1: msg = "WM_CREATE"
      Case &H2: msg = "WM_DESTROY"
      Case &H3: msg = "WM_MOVE"
      Case &H5: msg = "WM_SIZE"
      Case &H6: msg = "WM_ACTIVATE"
      Case &H7: msg = "WM_SETFOCUS"
      Case &H8: msg = "WM_KILLFOCUS"
      Case &HA: msg = "WM_ENABLE"
      Case &HB: msg = "WM_SETREDRAW"
      Case &HC: msg = "WM_SETTEXT"
      Case &HD: msg = "WM_GETTEXT"
      Case &HE: msg = "WM_GETTEXTLENGTH"
      Case &HF: msg = "WM_PAINT"
      Case &H10: msg = "WM_CLOSE"
      Case &H11: msg = "WM_QUERYENDSESSION"
      Case &H12: msg = "WM_QUIT"
      Case &H13: msg = "WM_QUERYOPEN"
      Case &H14: msg = "WM_ERASEBKGND"
      Case &H15: msg = "WM_SYSCOLORCHANGE"
      Case &H16: msg = "WM_ENDSESSION"
      Case &H18: msg = "WM_SHOWWINDOW"
      Case &H19: msg = "WM_CTLCOLOR"
      Case &H1A: msg = "WM_SETTINGCHANGE"
      Case &H1B: msg = "WM_DEVMODECHANGE"
      Case &H1C: msg = "WM_ACTIVATEAPP"
      Case &H1D: msg = "WM_FONTCHANGE"
      Case &H1E: msg = "WM_TIMECHANGE"
      Case &H1F: msg = "WM_CANCELMODE"
      Case &H20: msg = "WM_SETCURSOR"
      Case &H21: msg = "WM_MOUSEACTIVATE"
      Case &H22: msg = "WM_CHILDACTIVATE"
      Case &H23: msg = "WM_QUEUESYNC"
      Case &H24: msg = "WM_GETMINMAXINFO"
      Case &H26: msg = "WM_PAINTICON"
      Case &H27: msg = "WM_ICONERASEBKGND"
      Case &H28: msg = "WM_NEXTDLGCTL"
      Case &H2A: msg = "WM_SPOOLERSTATUS"
      Case &H2B: msg = "WM_DRAWITEM"
      Case &H2C: msg = "WM_MEASUREITEM"
      Case &H2D: msg = "WM_DELETEITEM"
      Case &H2E: msg = "WM_VKEYTOITEM"
      Case &H2F: msg = "WM_CHARTOITEM"
      Case &H30: msg = "WM_SETFONT"
      Case &H31: msg = "WM_GETFONT"
      Case &H32: msg = "WM_SETHOTKEY"
      Case &H33: msg = "WM_GETHOTKEY"
      Case &H37: msg = "WM_QUERYDRAGICON"
      Case &H39: msg = "WM_COMPAREITEM"
      Case &H3D: msg = "WM_GETOBJECT"
      Case &H41: msg = "WM_COMPACTING"
      Case &H44: msg = "WM_COMMNOTIFY"
      Case &H46: msg = "WM_WINDOWPOSCHANGING"
      Case &H47: msg = "WM_WINDOWPOSCHANGED"
      Case &H48: msg = "WM_POWER"
      Case &H4A: msg = "WM_COPYDATA"
      Case &H4B: msg = "WM_CANCELJOURNAL"
      Case &H4E: msg = "WM_NOTIFY"
      Case &H50: msg = "WM_INPUTLANGCHANGEREQUEST"
      Case &H51: msg = "WM_INPUTLANGCHANGE"
      Case &H52: msg = "WM_TCARD"
      Case &H53: msg = "WM_HELP"
      Case &H54: msg = "WM_USERCHANGED"
      Case &H55: msg = "WM_NOTIFYFORMAT"
      Case &H7B: msg = "WM_CONTEXTMENU"
      Case &H7C: msg = "WM_STYLECHANGING"
      Case &H7D: msg = "WM_STYLECHANGED"
      Case &H7E: msg = "WM_DISPLAYCHANGE"
      Case &H7F: msg = "WM_GETICON"
      Case &H80: msg = "WM_SETICON"
      Case &H81: msg = "WM_NCCREATE"
      Case &H82: msg = "WM_NCDESTROY"
      Case &H83: msg = "WM_NCCALCSIZE"
      Case &H84: msg = "WM_NCHITTEST"
      Case &H85: msg = "WM_NCPAINT"
      Case &H86: msg = "WM_NCACTIVATE"
      Case &H87: msg = "WM_GETDLGCODE"
      Case &H88: msg = "WM_SYNCPAINT"
      Case &HA0: msg = "WM_NCMOUSEMOVE"
      Case &HA1: msg = "WM_NCLBUTTONDOWN"
      Case &HA2: msg = "WM_NCLBUTTONUP"
      Case &HA3: msg = "WM_NCLBUTTONDBLCLK"
      Case &HA4: msg = "WM_NCRBUTTONDOWN"
      Case &HA5: msg = "WM_NCRBUTTONUP"
      Case &HA6: msg = "WM_NCRBUTTONDBLCLK"
      Case &HA7: msg = "WM_NCMBUTTONDOWN"
      Case &HA8: msg = "WM_NCMBUTTONUP"
      Case &HA9: msg = "WM_NCMBUTTONDBLCLK"
      Case &HAB: msg = "WM_NCXBUTTONDOWN"
      Case &HAC: msg = "WM_NCXBUTTONUP"
      Case &HAD: msg = "WM_NCXBUTTONDBLCLK"
      Case &HFF: msg = "WM_INPUT"
      Case &H100: msg = "WM_KEYDOWN"
      Case &H101: msg = "WM_KEYUP"
      Case &H102: msg = "WM_CHAR"
      Case &H103: msg = "WM_DEADCHAR"
      Case &H104: msg = "WM_SYSKEYDOWN"
      Case &H105: msg = "WM_SYSKEYUP"
      Case &H106: msg = "WM_SYSCHAR"
      Case &H107: msg = "WM_SYSDEADCHAR"
      Case &H108: msg = "WM_KEYLAST"
      Case &H10D: msg = "WM_IME_STARTCOMPOSITION"
      Case &H10E: msg = "WM_IME_ENDCOMPOSITION"
      Case &H10F: msg = "WM_IME_COMPOSITION"
      Case &H110: msg = "WM_INITDIALOG"
      Case &H111: msg = "WM_COMMAND"
      Case &H112: msg = "WM_SYSCOMMAND"
      Case &H113: msg = "WM_TIMER"
      Case &H114: msg = "WM_HSCROLL"
      Case &H115: msg = "WM_VSCROLL"
      Case &H116: msg = "WM_INITMENU"
      Case &H117: msg = "WM_INITMENUPOPUP"
      Case &H11F: msg = "WM_MENUSELECT"
      Case &H120: msg = "WM_MENUCHAR"
      Case &H121: msg = "WM_ENTERIDLE"
      Case &H122: msg = "WM_MENURBUTTONUP"
      Case &H123: msg = "WM_MENUDRAG"
      Case &H124: msg = "WM_MENUGETOBJECT"
      Case &H125: msg = "WM_UNINITMENUPOPUP"
      Case &H126: msg = "WM_MENUCOMMAND"
      Case &H127: msg = "WM_CHANGEUISTATE"
      Case &H128: msg = "WM_UPDATEUISTATE"
      Case &H129: msg = "WM_QUERYUISTATE"
      Case &H132: msg = "WM_CTLCOLORMSGBOX"
      Case &H133: msg = "WM_CTLCOLOREDIT"
      Case &H134: msg = "WM_CTLCOLORLISTBOX"
      Case &H135: msg = "WM_CTLCOLORBTN"
      Case &H136: msg = "WM_CTLCOLORDLG"
      Case &H137: msg = "WM_CTLCOLORSCROLLBAR"
      Case &H138: msg = "WM_CTLCOLORSTATIC"
      Case &H1E1: msg = "MN_GETHMENU"
      Case &H200: msg = "WM_MOUSEMOVE"
      Case &H201: msg = "WM_LBUTTONDOWN"
      Case &H202: msg = "WM_LBUTTONUP"
      Case &H203: msg = "WM_LBUTTONDBLCLK"
      Case &H204: msg = "WM_RBUTTONDOWN"
      Case &H205: msg = "WM_RBUTTONUP"
      Case &H206: msg = "WM_RBUTTONDBLCLK"
      Case &H207: msg = "WM_MBUTTONDOWN"
      Case &H208: msg = "WM_MBUTTONUP"
      Case &H209: msg = "WM_MBUTTONDBLCLK"
      Case &H20A: msg = "WM_MOUSEWHEEL"
      Case &H20B: msg = "WM_XBUTTONDOWN"
      Case &H20C: msg = "WM_XBUTTONUP"
      Case &H20D: msg = "WM_XBUTTONDBLCLK"
      Case &H210: msg = "WM_PARENTNOTIFY"
      Case &H211: msg = "WM_ENTERMENULOOP"
      Case &H212: msg = "WM_EXITMENULOOP"
      Case &H213: msg = "WM_NEXTMENU"
      Case &H214: msg = "WM_SIZING"
      Case &H215: msg = "WM_CAPTURECHANGED"
      Case &H216: msg = "WM_MOVING"
      Case &H218: msg = "WM_POWERBROADCAST"
      Case &H219: msg = "WM_DEVICECHANGE"
      Case &H220: msg = "WM_MDICREATE"
      Case &H221: msg = "WM_MDIDESTROY"
      Case &H222: msg = "WM_MDIACTIVATE"
      Case &H223: msg = "WM_MDIRESTORE"
      Case &H224: msg = "WM_MDINEXT"
      Case &H225: msg = "WM_MDIMAXIMIZE"
      Case &H226: msg = "WM_MDITILE"
      Case &H227: msg = "WM_MDICASCADE"
      Case &H228: msg = "WM_MDIICONARRANGE"
      Case &H229: msg = "WM_MDIGETACTIVE"
      Case &H230: msg = "WM_MDISETMENU"
      Case &H231: msg = "WM_ENTERSIZEMOVE"
      Case &H232: msg = "WM_EXITSIZEMOVE"
      Case &H233: msg = "WM_DROPFILES"
      Case &H234: msg = "WM_MDIREFRESHMENU"
      Case &H281: msg = "WM_IME_SETCONTEXT"
      Case &H282: msg = "WM_IME_NOTIFY"
      Case &H283: msg = "WM_IME_CONTROL"
      Case &H284: msg = "WM_IME_COMPOSITIONFULL"
      Case &H285: msg = "WM_IME_SELECT"
      Case &H286: msg = "WM_IME_CHAR"
      Case &H288: msg = "WM_IME_REQUEST"
      Case &H290: msg = "WM_IME_KEYDOWN"
      Case &H291: msg = "WM_IME_KEYUP"
      Case &H2A1: msg = "WM_MOUSEHOVER"
      Case &H2A3: msg = "WM_MOUSELEAVE"
      Case &H2A0: msg = "WM_NCMOUSEHOVER"
      Case &H2A2: msg = "WM_NCMOUSELEAVE"
      Case &H2B1: msg = "WM_WTSSESSION_CHANGE"
      Case &H2C0: msg = "WM_TABLET_FIRST"
      Case &H2DF: msg = "WM_TABLET_LAST"
      Case &H300: msg = "WM_CUT"
      Case &H301: msg = "WM_COPY"
      Case &H302: msg = "WM_PASTE"
      Case &H303: msg = "WM_CLEAR"
      Case &H304: msg = "WM_UNDO"
      Case &H305: msg = "WM_RENDERFORMAT"
      Case &H306: msg = "WM_RENDERALLFORMATS"
      Case &H307: msg = "WM_DESTROYCLIPBOARD"
      Case &H308: msg = "WM_DRAWCLIPBOARD"
      Case &H309: msg = "WM_PAINTCLIPBOARD"
      Case &H30A: msg = "WM_VSCROLLCLIPBOARD"
      Case &H30B: msg = "WM_SIZECLIPBOARD"
      Case &H30C: msg = "WM_ASKCBFORMATNAME"
      Case &H30D: msg = "WM_CHANGECBCHAIN"
      Case &H30E: msg = "WM_HSCROLLCLIPBOARD"
      Case &H30F: msg = "WM_QUERYNEWPALETTE"
      Case &H310: msg = "WM_PALETTEISCHANGING"
      Case &H311: msg = "WM_PALETTECHANGED"
      Case &H312: msg = "WM_HOTKEY"
      Case &H317: msg = "WM_PRINT"
      Case &H318: msg = "WM_PRINTCLIENT"
      Case &H319: msg = "WM_APPCOMMAND"
      Case &H31A: msg = "WM_THEMECHANGED"
      Case &H358: msg = "WM_HANDHELDFIRST"
      Case &H35F: msg = "WM_HANDHELDLAST"
      Case &H360: msg = "WM_AFXFIRST"
      Case &H37F: msg = "WM_AFXLAST"
      Case &H380: msg = "WM_PENWINFIRST"
      Case &H38F: msg = "WM_PENWINLAST"
      Case &H400: msg = "WM_USER"
      
      Case &H4C8: msg = "EM_SETBIDIOPTIONS"
      Case &H4C9: msg = "EM_GETBIDIOPTIONS"
      Case &H4CA: msg = "EM_SETTYPOGRAPHYOPTIONS"
      Case &H4CB: msg = "EM_GETTYPOGRAPHYOPTIONS"
      Case &H4CC: msg = "EM_SETEDITSTYLE"
      Case &H4CD: msg = "EM_GETEDITSTYLE"
      Case &H425: msg = "EM_GETLIMITTEXT"
      Case &H426: msg = "EM_POSFROMCHAR"
      Case &H427: msg = "EM_CHARFROMPOS"
      Case &H431: msg = "EM_SCROLLCARET"
      Case &H432: msg = "EM_CANPASTE"
      Case &H433: msg = "EM_DISPLAYBAND"
      Case &H434: msg = "EM_EXGETSEL"
      Case &H435: msg = "EM_EXLIMITTEXT"
      Case &H436: msg = "EM_EXLINEFROMCHAR"
      Case &H437: msg = "EM_EXSETSEL"
      Case &H438: msg = "EM_FINDTEXT"
      Case &H439: msg = "EM_FORMATRANGE"
      Case &H43A: msg = "EM_GETCHARFORMAT"
      Case &H43B: msg = "EM_GETEVENTMASK"
      Case &H43C: msg = "EM_GETOLEINTERFACE"
      Case &H43D: msg = "EM_GETPARAFORMAT"
      Case &H43E: msg = "EM_GETSELTEXT"
      Case &H43F: msg = "EM_HIDESELECTION"
      Case &H440: msg = "EM_PASTESPECIAL"
      Case &H441: msg = "EM_REQUESTRESIZE"
      Case &H442: msg = "EM_SELECTIONTYPE"
      Case &H443: msg = "EM_SETBKGNDCOLOR"
      Case &H444: msg = "EM_SETCHARFORMAT"
      Case &H445: msg = "EM_SETEVENTMASK"
      Case &H446: msg = "EM_SETOLECALLBACK"
      Case &H447: msg = "EM_SETPARAFORMAT"
      Case &H448: msg = "EM_SETTARGETDEVICE"
      Case &H449: msg = "EM_STREAMIN"
      Case &H44A: msg = "EM_STREAMOUT"
      Case &H44B: msg = "EM_GETTEXTRANGE"
      Case &H44C: msg = "EM_FINDWORDBREAK"
      Case &H44D: msg = "EM_SETOPTIONS"
      Case &H44E: msg = "EM_GETOPTIONS"
      Case &H44F: msg = "EM_FINDTEXTEX"
      Case &H450: msg = "EM_GETWORDBREAKPROCEX"
      Case &H451: msg = "EM_SETWORDBREAKPROCEX"
      Case &H452: msg = "EM_SETUNDOLIMIT"
      Case &H454: msg = "EM_REDO"
      Case &H455: msg = "EM_CANREDO"
      Case &H456: msg = "EM_GETUNDONAME"
      Case &H457: msg = "EM_GETREDONAME"
      Case &H458: msg = "EM_STOPGROUPTYPING"
      Case &H459: msg = "EM_SETTEXTMODE"
      Case &H45A: msg = "EM_GETTEXTMODE"
      Case &H45B: msg = "EM_AUTOURLDETECT"
      Case &H45C: msg = "EM_GETAUTOURLDETECT"
      Case &H45D: msg = "EM_SETPALETTE"
      Case &H45E: msg = "EM_GETTEXTEX"
      Case &H45F: msg = "EM_GETTEXTLENGTHEX"
      Case &H464: msg = "EM_SETPUNCTUATION"
      Case &H465: msg = "EM_GETPUNCTUATION"
      Case &H466: msg = "EM_SETWORDWRAPMODE"
      Case &H467: msg = "EM_GETWORDWRAPMODE"
      Case &H468: msg = "EM_SETIMECOLOR"
      Case &H469: msg = "EM_GETIMECOLOR"
      Case &H46A: msg = "EM_SETIMEOPTIONS"
      Case &H46B: msg = "EM_GETIMEOPTIONS"
      Case &H46C: msg = "EM_CONVPOSITION"
      Case &H478: msg = "EM_SETLANGOPTIONS"
      Case &H479: msg = "EM_GETLANGOPTIONS"
      Case &H47A: msg = "EM_GETIMECOMPMODE"
      Case &H47B: msg = "EM_FINDTEXTW"
      Case &H47C: msg = "EM_FINDTEXTEXW"
      Case &H47D: msg = "EM_RECONVERSION"
      Case &H47E: msg = "EM_SETIMEMODEBIAS"
      Case &H47F: msg = "EM_GETIMEMODEBIAS"
      
      Case Else: msg = "&h" & Right$(String$(4, "0") & Hex$(nMsg), 4)
   End Select
   GetMessageName = msg
End Function

Public Function GetParameterName(ByVal nMsg As Long) As String
   Dim msg As String
   Select Case nMsg
      Case &H1: msg = "SPI_GETBEEP"
      Case &H2: msg = "SPI_SETBEEP"
      Case &H3: msg = "SPI_GETMOUSE"
      Case &H4: msg = "SPI_SETMOUSE"
      Case &H5: msg = "SPI_GETBORDER"
      Case &H6: msg = "SPI_SETBORDER"
      Case &HA: msg = "SPI_GETKEYBOARDSPEED"
      Case &HB: msg = "SPI_SETKEYBOARDSPEED"
      Case &HC: msg = "SPI_LANGDRIVER"
      Case &HD: msg = "SPI_ICONHORIZONTALSPACING"
      Case &HE: msg = "SPI_GETSCREENSAVETIMEOUT"
      Case &HF: msg = "SPI_SETSCREENSAVETIMEOUT"
      Case &H10: msg = "SPI_GETSCREENSAVEACTIVE"
      Case &H11: msg = "SPI_SETSCREENSAVEACTIVE"
      Case &H12: msg = "SPI_GETGRIDGRANULARITY"
      Case &H13: msg = "SPI_SETGRIDGRANULARITY"
      Case &H14: msg = "SPI_SETDESKWALLPAPER"
      Case &H15: msg = "SPI_SETDESKPATTERN"
      Case &H16: msg = "SPI_GETKEYBOARDDELAY"
      Case &H17: msg = "SPI_SETKEYBOARDDELAY"
      Case &H18: msg = "SPI_ICONVERTICALSPACING"
      Case &H19: msg = "SPI_GETICONTITLEWRAP"
      Case &H1A: msg = "SPI_SETICONTITLEWRAP"
      Case &H1B: msg = "SPI_GETMENUDROPALIGNMENT"
      Case &H1C: msg = "SPI_SETMENUDROPALIGNMENT"
      Case &H1D: msg = "SPI_SETDOUBLECLKWIDTH"
      Case &H1E: msg = "SPI_SETDOUBLECLKHEIGHT"
      Case &H1F: msg = "SPI_GETICONTITLELOGFONT"
      Case &H20: msg = "SPI_SETDOUBLECLICKTIME"
      Case &H21: msg = "SPI_SETMOUSEBUTTONSWAP"
      Case &H22: msg = "SPI_SETICONTITLELOGFONT"
      Case &H23: msg = "SPI_GETFASTTASKSWITCH"
      Case &H24: msg = "SPI_SETFASTTASKSWITCH"
      Case &H25: msg = "SPI_SETDRAGFULLWINDOWS"
      Case &H26: msg = "SPI_GETDRAGFULLWINDOWS"
      Case &H29: msg = "SPI_GETNONCLIENTMETRICS"
      Case &H2A: msg = "SPI_SETNONCLIENTMETRICS"
      Case &H2B: msg = "SPI_GETMINIMIZEDMETRICS"
      Case &H2C: msg = "SPI_SETMINIMIZEDMETRICS"
      Case &H2D: msg = "SPI_GETICONMETRICS"
      Case &H2E: msg = "SPI_SETICONMETRICS"
      Case &H2F: msg = "SPI_SETWORKAREA"
      Case &H30: msg = "SPI_GETWORKAREA"
      Case &H31: msg = "SPI_SETPENWINDOWS"
      Case &H42: msg = "SPI_GETHIGHCONTRAST"
      Case &H43: msg = "SPI_SETHIGHCONTRAST"
      Case &H44: msg = "SPI_GETKEYBOARDPREF"
      Case &H45: msg = "SPI_SETKEYBOARDPREF"
      Case &H46: msg = "SPI_GETSCREENREADER"
      Case &H47: msg = "SPI_SETSCREENREADER"
      Case &H48: msg = "SPI_GETANIMATION"
      Case &H49: msg = "SPI_SETANIMATION"
      Case &H4A: msg = "SPI_GETFONTSMOOTHING"
      Case &H4B: msg = "SPI_SETFONTSMOOTHING"
      Case &H4C: msg = "SPI_SETDRAGWIDTH"
      Case &H4D: msg = "SPI_SETDRAGHEIGHT"
      Case &H4E: msg = "SPI_SETHANDHELD"
      Case &H4F: msg = "SPI_GETLOWPOWERTIMEOUT"
      Case &H50: msg = "SPI_GETPOWEROFFTIMEOUT"
      Case &H51: msg = "SPI_SETLOWPOWERTIMEOUT"
      Case &H52: msg = "SPI_SETPOWEROFFTIMEOUT"
      Case &H53: msg = "SPI_GETLOWPOWERACTIVE"
      Case &H54: msg = "SPI_GETPOWEROFFACTIVE"
      Case &H55: msg = "SPI_SETLOWPOWERACTIVE"
      Case &H56: msg = "SPI_SETPOWEROFFACTIVE"
      Case &H57: msg = "SPI_SETCURSORS"
      Case &H58: msg = "SPI_SETICONS"
      Case &H59: msg = "SPI_GETDEFAULTINPUTLANG"
      Case &H5A: msg = "SPI_SETDEFAULTINPUTLANG"
      Case &H5B: msg = "SPI_SETLANGTOGGLE"
      Case &H5C: msg = "SPI_GETWINDOWSEXTENSION"
      Case &H5D: msg = "SPI_SETMOUSETRAILS"
      Case &H5E: msg = "SPI_GETMOUSETRAILS"
      Case &H61: msg = "SPI_SETSCREENSAVERRUNNING"
      Case &H32: msg = "SPI_GETFILTERKEYS"
      Case &H33: msg = "SPI_SETFILTERKEYS"
      Case &H34: msg = "SPI_GETTOGGLEKEYS"
      Case &H35: msg = "SPI_SETTOGGLEKEYS"
      Case &H36: msg = "SPI_GETMOUSEKEYS"
      Case &H37: msg = "SPI_SETMOUSEKEYS"
      Case &H38: msg = "SPI_GETSHOWSOUNDS"
      Case &H39: msg = "SPI_SETSHOWSOUNDS"
      Case &H3A: msg = "SPI_GETSTICKYKEYS"
      Case &H3B: msg = "SPI_SETSTICKYKEYS"
      Case &H3C: msg = "SPI_GETACCESSTIMEOUT"
      Case &H3D: msg = "SPI_SETACCESSTIMEOUT"
      Case &H3E: msg = "SPI_GETSERIALKEYS"
      Case &H3F: msg = "SPI_SETSERIALKEYS"
      Case &H40: msg = "SPI_GETSOUNDSENTRY"
      Case &H41: msg = "SPI_SETSOUNDSENTRY"
      Case &H5F: msg = "SPI_GETSNAPTODEFBUTTON"
      Case &H60: msg = "SPI_SETSNAPTODEFBUTTON"
      Case &H62: msg = "SPI_GETMOUSEHOVERWIDTH"
      Case &H63: msg = "SPI_SETMOUSEHOVERWIDTH"
      Case &H64: msg = "SPI_GETMOUSEHOVERHEIGHT"
      Case &H65: msg = "SPI_SETMOUSEHOVERHEIGHT"
      Case &H66: msg = "SPI_GETMOUSEHOVERTIME"
      Case &H67: msg = "SPI_SETMOUSEHOVERTIME"
      Case &H68: msg = "SPI_GETWHEELSCROLLLINES"
      Case &H69: msg = "SPI_SETWHEELSCROLLLINES"
      Case &H6A: msg = "SPI_GETMENUSHOWDELAY"
      Case &H6B: msg = "SPI_SETMENUSHOWDELAY"
      Case &H6E: msg = "SPI_GETSHOWIMEUI"
      Case &H6F: msg = "SPI_SETSHOWIMEUI"
      Case &H70: msg = "SPI_GETMOUSESPEED"
      Case &H71: msg = "SPI_SETMOUSESPEED"
      Case &H72: msg = "SPI_GETSCREENSAVERRUNNING"
      Case &H73: msg = "SPI_GETDESKWALLPAPER"
      Case &H1000: msg = "SPI_GETACTIVEWINDOWTRACKING"
      Case &H1001: msg = "SPI_SETACTIVEWINDOWTRACKING"
      Case &H1002: msg = "SPI_GETMENUANIMATION"
      Case &H1003: msg = "SPI_SETMENUANIMATION"
      Case &H1004: msg = "SPI_GETCOMBOBOXANIMATION"
      Case &H1005: msg = "SPI_SETCOMBOBOXANIMATION"
      Case &H1006: msg = "SPI_GETLISTBOXSMOOTHSCROLLING"
      Case &H1007: msg = "SPI_SETLISTBOXSMOOTHSCROLLING"
      Case &H1008: msg = "SPI_GETGRADIENTCAPTIONS"
      Case &H1009: msg = "SPI_SETGRADIENTCAPTIONS"
      Case &H100A: msg = "SPI_GETKEYBOARDCUES"
      Case &H100B: msg = "SPI_SETKEYBOARDCUES"
      Case &H100C: msg = "SPI_GETACTIVEWNDTRKZORDER"
      Case &H100D: msg = "SPI_SETACTIVEWNDTRKZORDER"
      Case &H100E: msg = "SPI_GETHOTTRACKING"
      Case &H100F: msg = "SPI_SETHOTTRACKING"
      Case &H1012: msg = "SPI_GETMENUFADE"
      Case &H1013: msg = "SPI_SETMENUFADE"
      Case &H1014: msg = "SPI_GETSELECTIONFADE"
      Case &H1015: msg = "SPI_SETSELECTIONFADE"
      Case &H1016: msg = "SPI_GETTOOLTIPANIMATION"
      Case &H1017: msg = "SPI_SETTOOLTIPANIMATION"
      Case &H1018: msg = "SPI_GETTOOLTIPFADE"
      Case &H1019: msg = "SPI_SETTOOLTIPFADE"
      Case &H101A: msg = "SPI_GETCURSORSHADOW"
      Case &H101B: msg = "SPI_SETCURSORSHADOW"
      Case &H101C: msg = "SPI_GETMOUSESONAR"
      Case &H101D: msg = "SPI_SETMOUSESONAR"
      Case &H101E: msg = "SPI_GETMOUSECLICKLOCK"
      Case &H101F: msg = "SPI_SETMOUSECLICKLOCK"
      Case &H1020: msg = "SPI_GETMOUSEVANISH"
      Case &H1021: msg = "SPI_SETMOUSEVANISH"
      Case &H1022: msg = "SPI_GETFLATMENU"
      Case &H1023: msg = "SPI_SETFLATMENU"
      Case &H1024: msg = "SPI_GETDROPSHADOW"
      Case &H1025: msg = "SPI_SETDROPSHADOW"
      Case &H1026: msg = "SPI_GETBLOCKSENDINPUTRESETS"
      Case &H1027: msg = "SPI_SETBLOCKSENDINPUTRESETS"
      Case &H103E: msg = "SPI_GETUIEFFECTS"
      Case &H103F: msg = "SPI_SETUIEFFECTS"
      Case &H2000: msg = "SPI_GETFOREGROUNDLOCKTIMEOUT"
      Case &H2001: msg = "SPI_SETFOREGROUNDLOCKTIMEOUT"
      Case &H2002: msg = "SPI_GETACTIVEWNDTRKTIMEOUT"
      Case &H2003: msg = "SPI_SETACTIVEWNDTRKTIMEOUT"
      Case &H2004: msg = "SPI_GETFOREGROUNDFLASHCOUNT"
      Case &H2005: msg = "SPI_SETFOREGROUNDFLASHCOUNT"
      Case &H2006: msg = "SPI_GETCARETWIDTH"
      Case &H2007: msg = "SPI_SETCARETWIDTH"
      Case &H2008: msg = "SPI_GETMOUSECLICKLOCKTIME"
      Case &H2009: msg = "SPI_SETMOUSECLICKLOCKTIME"
      Case &H200A: msg = "SPI_GETFONTSMOOTHINGTYPE"
      Case &H200B: msg = "SPI_SETFONTSMOOTHINGTYPE"
      Case &H8000: msg = "FE_FONTSMOOTHINGDOCKING"
      Case &H200C: msg = "SPI_GETFONTSMOOTHINGCONTRAST"
      Case &H200D: msg = "SPI_SETFONTSMOOTHINGCONTRAST"
      Case &H200E: msg = "SPI_GETFOCUSBORDERWIDTH"
      Case &H200F: msg = "SPI_SETFOCUSBORDERWIDTH"
      Case &H2010: msg = "SPI_GETFOCUSBORDERHEIGHT"
      Case &H2011: msg = "SPI_SETFOCUSBORDERHEIGHT"
      Case &H2012: msg = "SPI_GETFONTSMOOTHINGORIENTATION"
      Case &H2013: msg = "SPI_SETFONTSMOOTHINGORIENTATION"

      Case Else: msg = "&h" & Right$(String$(4, "0") & Hex$(nMsg), 4)
   End Select
   GetParameterName = msg
End Function

Public Function MessageNames() As String()
   ReDim arr(WM_NULL To WM_USER) As String
   arr(&H0) = "WM_NULL"
   arr(&H1) = "WM_CREATE"
   arr(&H2) = "WM_DESTROY"
   arr(&H3) = "WM_MOVE"
   arr(&H5) = "WM_SIZE"
   arr(&H6) = "WM_ACTIVATE"
   arr(&H7) = "WM_SETFOCUS"
   arr(&H8) = "WM_KILLFOCUS"
   arr(&HA) = "WM_ENABLE"
   arr(&HB) = "WM_SETREDRAW"
   arr(&HC) = "WM_SETTEXT"
   arr(&HD) = "WM_GETTEXT"
   arr(&HE) = "WM_GETTEXTLENGTH"
   arr(&HF) = "WM_PAINT"
   arr(&H10) = "WM_CLOSE"
   arr(&H11) = "WM_QUERYENDSESSION"
   arr(&H12) = "WM_QUIT"
   arr(&H13) = "WM_QUERYOPEN"
   arr(&H14) = "WM_ERASEBKGND"
   arr(&H15) = "WM_SYSCOLORCHANGE"
   arr(&H16) = "WM_ENDSESSION"
   arr(&H18) = "WM_SHOWWINDOW"
   arr(&H1A) = "WM_SETTINGCHANGE"
   arr(&H1B) = "WM_DEVMODECHANGE"
   arr(&H1C) = "WM_ACTIVATEAPP"
   arr(&H1D) = "WM_FONTCHANGE"
   arr(&H1E) = "WM_TIMECHANGE"
   arr(&H1F) = "WM_CANCELMODE"
   arr(&H20) = "WM_SETCURSOR"
   arr(&H21) = "WM_MOUSEACTIVATE"
   arr(&H22) = "WM_CHILDACTIVATE"
   arr(&H23) = "WM_QUEUESYNC"
   arr(&H24) = "WM_GETMINMAXINFO"
   arr(&H26) = "WM_PAINTICON"
   arr(&H27) = "WM_ICONERASEBKGND"
   arr(&H28) = "WM_NEXTDLGCTL"
   arr(&H2A) = "WM_SPOOLERSTATUS"
   arr(&H2B) = "WM_DRAWITEM"
   arr(&H2C) = "WM_MEASUREITEM"
   arr(&H2D) = "WM_DELETEITEM"
   arr(&H2E) = "WM_VKEYTOITEM"
   arr(&H2F) = "WM_CHARTOITEM"
   arr(&H30) = "WM_SETFONT"
   arr(&H31) = "WM_GETFONT"
   arr(&H32) = "WM_SETHOTKEY"
   arr(&H33) = "WM_GETHOTKEY"
   arr(&H37) = "WM_QUERYDRAGICON"
   arr(&H39) = "WM_COMPAREITEM"
   arr(&H3D) = "WM_GETOBJECT"
   arr(&H41) = "WM_COMPACTING"
   arr(&H44) = "WM_COMMNOTIFY"
   arr(&H46) = "WM_WINDOWPOSCHANGING"
   arr(&H47) = "WM_WINDOWPOSCHANGED"
   arr(&H48) = "WM_POWER"
   arr(&H4A) = "WM_COPYDATA"
   arr(&H4B) = "WM_CANCELJOURNAL"
   arr(&H4E) = "WM_NOTIFY"
   arr(&H50) = "WM_INPUTLANGCHANGEREQUEST"
   arr(&H51) = "WM_INPUTLANGCHANGE"
   arr(&H52) = "WM_TCARD"
   arr(&H53) = "WM_HELP"
   arr(&H54) = "WM_USERCHANGED"
   arr(&H55) = "WM_NOTIFYFORMAT"
   arr(&H7B) = "WM_CONTEXTMENU"
   arr(&H7C) = "WM_STYLECHANGING"
   arr(&H7D) = "WM_STYLECHANGED"
   arr(&H7E) = "WM_DISPLAYCHANGE"
   arr(&H7F) = "WM_GETICON"
   arr(&H80) = "WM_SETICON"
   arr(&H81) = "WM_NCCREATE"
   arr(&H82) = "WM_NCDESTROY"
   arr(&H83) = "WM_NCCALCSIZE"
   arr(&H84) = "WM_NCHITTEST"
   arr(&H85) = "WM_NCPAINT"
   arr(&H86) = "WM_NCACTIVATE"
   arr(&H87) = "WM_GETDLGCODE"
   arr(&H88) = "WM_SYNCPAINT"
   arr(&HA0) = "WM_NCMOUSEMOVE"
   arr(&HA1) = "WM_NCLBUTTONDOWN"
   arr(&HA2) = "WM_NCLBUTTONUP"
   arr(&HA3) = "WM_NCLBUTTONDBLCLK"
   arr(&HA4) = "WM_NCRBUTTONDOWN"
   arr(&HA5) = "WM_NCRBUTTONUP"
   arr(&HA6) = "WM_NCRBUTTONDBLCLK"
   arr(&HA7) = "WM_NCMBUTTONDOWN"
   arr(&HA8) = "WM_NCMBUTTONUP"
   arr(&HA9) = "WM_NCMBUTTONDBLCLK"
   arr(&HAB) = "WM_NCXBUTTONDOWN"
   arr(&HAC) = "WM_NCXBUTTONUP"
   arr(&HAD) = "WM_NCXBUTTONDBLCLK"
   arr(&HFF) = "WM_INPUT"
   arr(&H100) = "WM_KEYDOWN"
   arr(&H101) = "WM_KEYUP"
   arr(&H102) = "WM_CHAR"
   arr(&H103) = "WM_DEADCHAR"
   arr(&H104) = "WM_SYSKEYDOWN"
   arr(&H105) = "WM_SYSKEYUP"
   arr(&H106) = "WM_SYSCHAR"
   arr(&H107) = "WM_SYSDEADCHAR"
   arr(&H10D) = "WM_IME_STARTCOMPOSITION"
   arr(&H10E) = "WM_IME_ENDCOMPOSITION"
   arr(&H10F) = "WM_IME_COMPOSITION"
   arr(&H110) = "WM_INITDIALOG"
   arr(&H111) = "WM_COMMAND"
   arr(&H112) = "WM_SYSCOMMAND"
   arr(&H113) = "WM_TIMER"
   arr(&H114) = "WM_HSCROLL"
   arr(&H115) = "WM_VSCROLL"
   arr(&H116) = "WM_INITMENU"
   arr(&H117) = "WM_INITMENUPOPUP"
   arr(&H11F) = "WM_MENUSELECT"
   arr(&H120) = "WM_MENUCHAR"
   arr(&H121) = "WM_ENTERIDLE"
   arr(&H122) = "WM_MENURBUTTONUP"
   arr(&H123) = "WM_MENUDRAG"
   arr(&H124) = "WM_MENUGETOBJECT"
   arr(&H125) = "WM_UNINITMENUPOPUP"
   arr(&H126) = "WM_MENUCOMMAND"
   arr(&H127) = "WM_CHANGEUISTATE"
   arr(&H128) = "WM_UPDATEUISTATE"
   arr(&H129) = "WM_QUERYUISTATE"
   arr(&H132) = "WM_CTLCOLORMSGBOX"
   arr(&H133) = "WM_CTLCOLOREDIT"
   arr(&H134) = "WM_CTLCOLORLISTBOX"
   arr(&H135) = "WM_CTLCOLORBTN"
   arr(&H136) = "WM_CTLCOLORDLG"
   arr(&H137) = "WM_CTLCOLORSCROLLBAR"
   arr(&H138) = "WM_CTLCOLORSTATIC"
   arr(&H1E1) = "MN_GETHMENU"
   arr(&H200) = "WM_MOUSEMOVE"
   arr(&H201) = "WM_LBUTTONDOWN"
   arr(&H202) = "WM_LBUTTONUP"
   arr(&H203) = "WM_LBUTTONDBLCLK"
   arr(&H204) = "WM_RBUTTONDOWN"
   arr(&H205) = "WM_RBUTTONUP"
   arr(&H206) = "WM_RBUTTONDBLCLK"
   arr(&H207) = "WM_MBUTTONDOWN"
   arr(&H208) = "WM_MBUTTONUP"
   arr(&H209) = "WM_MBUTTONDBLCLK"
   arr(&H20A) = "WM_MOUSEWHEEL"
   arr(&H20B) = "WM_XBUTTONDOWN"
   arr(&H20C) = "WM_XBUTTONUP"
   arr(&H20D) = "WM_XBUTTONDBLCLK"
   arr(&H210) = "WM_PARENTNOTIFY"
   arr(&H211) = "WM_ENTERMENULOOP"
   arr(&H212) = "WM_EXITMENULOOP"
   arr(&H213) = "WM_NEXTMENU"
   arr(&H214) = "WM_SIZING"
   arr(&H215) = "WM_CAPTURECHANGED"
   arr(&H216) = "WM_MOVING"
   arr(&H218) = "WM_POWERBROADCAST"
   arr(&H219) = "WM_DEVICECHANGE"
   arr(&H220) = "WM_MDICREATE"
   arr(&H221) = "WM_MDIDESTROY"
   arr(&H222) = "WM_MDIACTIVATE"
   arr(&H223) = "WM_MDIRESTORE"
   arr(&H224) = "WM_MDINEXT"
   arr(&H225) = "WM_MDIMAXIMIZE"
   arr(&H226) = "WM_MDITILE"
   arr(&H227) = "WM_MDICASCADE"
   arr(&H228) = "WM_MDIICONARRANGE"
   arr(&H229) = "WM_MDIGETACTIVE"
   arr(&H230) = "WM_MDISETMENU"
   arr(&H231) = "WM_ENTERSIZEMOVE"
   arr(&H232) = "WM_EXITSIZEMOVE"
   arr(&H233) = "WM_DROPFILES"
   arr(&H234) = "WM_MDIREFRESHMENU"
   arr(&H281) = "WM_IME_SETCONTEXT"
   arr(&H282) = "WM_IME_NOTIFY"
   arr(&H283) = "WM_IME_CONTROL"
   arr(&H284) = "WM_IME_COMPOSITIONFULL"
   arr(&H285) = "WM_IME_SELECT"
   arr(&H286) = "WM_IME_CHAR"
   arr(&H288) = "WM_IME_REQUEST"
   arr(&H290) = "WM_IME_KEYDOWN"
   arr(&H291) = "WM_IME_KEYUP"
   arr(&H2A1) = "WM_MOUSEHOVER"
   arr(&H2A3) = "WM_MOUSELEAVE"
   arr(&H2A0) = "WM_NCMOUSEHOVER"
   arr(&H2A2) = "WM_NCMOUSELEAVE"
   arr(&H2B1) = "WM_WTSSESSION_CHANGE"
   arr(&H2C0) = "WM_TABLET_FIRST"
   arr(&H2DF) = "WM_TABLET_LAST"
   arr(&H300) = "WM_CUT"
   arr(&H301) = "WM_COPY"
   arr(&H302) = "WM_PASTE"
   arr(&H303) = "WM_CLEAR"
   arr(&H304) = "WM_UNDO"
   arr(&H305) = "WM_RENDERFORMAT"
   arr(&H306) = "WM_RENDERALLFORMATS"
   arr(&H307) = "WM_DESTROYCLIPBOARD"
   arr(&H308) = "WM_DRAWCLIPBOARD"
   arr(&H309) = "WM_PAINTCLIPBOARD"
   arr(&H30A) = "WM_VSCROLLCLIPBOARD"
   arr(&H30B) = "WM_SIZECLIPBOARD"
   arr(&H30C) = "WM_ASKCBFORMATNAME"
   arr(&H30D) = "WM_CHANGECBCHAIN"
   arr(&H30E) = "WM_HSCROLLCLIPBOARD"
   arr(&H30F) = "WM_QUERYNEWPALETTE"
   arr(&H310) = "WM_PALETTEISCHANGING"
   arr(&H311) = "WM_PALETTECHANGED"
   arr(&H312) = "WM_HOTKEY"
   arr(&H317) = "WM_PRINT"
   arr(&H318) = "WM_PRINTCLIENT"
   arr(&H319) = "WM_APPCOMMAND"
   arr(&H31A) = "WM_THEMECHANGED"
   arr(&H358) = "WM_HANDHELDFIRST"
   arr(&H35F) = "WM_HANDHELDLAST"
   arr(&H360) = "WM_AFXFIRST"
   arr(&H37F) = "WM_AFXLAST"
   arr(&H380) = "WM_PENWINFIRST"
   arr(&H38F) = "WM_PENWINLAST"
   arr(&H400) = "WM_USER"
   MessageNames = arr
End Function

